### ISSUE TITLE
Issue with Chromium's Application Cache

### ISSUE THREAD

**Issue by ghost** [SpaceApi-archive/SpaceApi#13]
When I use chrome, the 'new space' and 'directory' links do not show and the validator bombs.

**Comment by lhw** [comment]
Current Chromium stable release 18.0.1025.151 (Developer Build 130497 Linux)  works fine. Should be identical to a Chrome release of the same version number. You might have NoScript or similar enabled which renders the site pretty much useless as everything is done via javascript.

**Comment by ghost** [comment]
This is the error i get in the chrome javascript console:

Document was loaded from Application Cache with manifest http://openspace.slopjong.de/jsonlint.manifest
Application Cache Checking event
Uncaught SyntaxError: Unexpected token < error.html:1
Application Cache Error event: Manifest fetch failed (-1) http://openspace.slopjong.de/jsonlint.manifest

Version 19.0.1084.46

**Comment by slopjong** [comment]
Exactly that version works perfectly with the directory on my machine. jsonlint.manifest was removed a long time ago but it might be still stored in your cache. Did you try to clear your cache?

**Comment by ghost** [comment]
Yes, I clear the cache and all history routinely. I just cleared everything explicitly again, but still getting the error.

**Comment by slopjong** [comment]
Not your regular cache but your application cache. Have a look here: chrome://appcache-internals/

Your error means that the manifest file cannot be loaded from the server which is correct because I removed it many many weeks ago. Your chrome still has an application entry for offline use.

**Comment by slopjong** [comment]
I've updated the title to "Issue with the Application Cache" because the problem is not a compatibility one but with an old entry in the application cache.

**Comment by ghost** [comment]
Yep, that seems to have fixed it..

**Comment by ghost** [comment]
Closed..
