### ISSUE TITLE
Directory unavailable due to server maintenance on May 25th

### ISSUE THREAD

**Issue by slopjong** [SpaceApi-archive/SpaceApi#14]
There's a server maintenance on May 25th from 2:00 to 5:00 UTC+2

Some hardware will be replaced. Such a maintenance happens once per year at most (from my experience every 2 years) but I'm sorry for that 3 hours.

**Comment by tdfischer** [comment]
...is this still open?

**Comment by eastein** [comment]
Thanks @tdfischer clearly this is moot now.
