### ISSUE TITLE
New draft being worked out and presented @haxogreen

### ISSUE THREAD

**Issue by slopjong** [SpaceApi-archive/SpaceApi#17]
I was out of time so I didn't work much on the API in the past weeks. All the improvements I've kept in mind will be worked out in a draft and presented on the haxogreen (http://haxogreen.lu) conference on July, 27th.

If you can't be there, let's have a chat on freenode.

**Comment by rrix** [comment]
Definitely interested in this discussion; @eastein and I have discussed very briefly where we feel the API should expand to, and I'm currently drafting out some improvements on it for HeatSync Labs.

**Comment by eastein** [comment]
I wouldn't mind seeing your changes before ahead of time (i'd keep them to myself if you want all the splash) as I'm sure @rrix would as well; sometimes API design is something you should check with a couple people to make sure you've not made a mistake before you show it off to a whole conference; it's very difficult to change APIs.

I'm sure you've got something awesome up your sleeve, from our conversations on the Pumping Station: One channel.  I can't wait to hear about it.

**Comment by slopjong** [comment]
I'll prepare it within next two weeks.

**Comment by slopjong** [comment]
Closing this ticket. @rrix and @eastein , please open a new ticket [here](https://github.com/SpaceApi/OpenSpaceSchema) for your improvements. That's the repo where I'll push the new specs.
