### ISSUE TITLE
Must the 'icon' field be mandatory?

### ISSUE THREAD

**Issue by slopjong** [SpaceApi-archive/SpaceApi#18]
What thoughts are behind having the 'icon' field being mandatory?

From my point of view it could be optional. Are there apps which rely heavily on it? I think most apps evaluate the 'open' field and use their own icon set to display it.

**Comment by rrix** [comment]
The hackerspaces.me wall uses it and I don't see why it is so difficult to associate an icon with it?

What are the reasons/usecases of making it optional?

**Comment by slopjong** [comment]
My thought was that all the apps I knew or remembered were evaluating the 'open' field and using their own icon set. I simply forgot your wall.

I see some spaces missing that fields or at least what was cached is missing those. In your case you could fetch the directory as follows:

http://openspace.slopjong.de/directory.json?filter=and(icon.open,icon.closed)

**Comment by slopjong** [comment]
Discussion ended a year ago.
