### ISSUE TITLE
add google service contact entries

### ISSUE THREAD

**Issue by haxwithaxe** [SpaceApi-archive/SpaceApi#19]
proposing format of "google.<service>" such as "google.plus" "google.groups" etc
this is how the HacDC feed will implement it until the spec for it is declared.

**Comment by slopjong** [comment]
Everything not covered by the specs should be considered to be optional. I'm currently busy but I'll work out the next version which I'm discussing at the HaxoGreen (http://haxogreen.lu). During or after the conf I'll implement the new specs in OpenSpaceLint (http://openspace.slopjong.de).

In short, you can add as many JSON fields as you want, they appear in the filters list automatically after you added yourself to the directory. You're still missing there ;-)

**Comment by slopjong** [comment]
I see that you no longer have google fields, can I close this ticket?

Every hackerspace can add new fields but they must be prefixed with <code>ext_</code>. In some future the validator won't accept non-specified fields that don't start with that prefix.

**Comment by slopjong** [comment]
I've added google.plus. Many spaces are using the ml field for their google group so it doesn't make sense to add google.groups. If you think it should be added I'll add it while you ask the spaces usig ml for it to use the new field. Are you fine with this?

The new field will be available on the website after the next deployment.

**Comment by btittelbach** [comment]
would definitely be useful in our case
