### ISSUE TITLE
Image not shown with trailing slash in the URL

### ISSUE THREAD

**Issue by slopjong** [SpaceApi-archive/SpaceApi#29]
Currently some images are linked relative to their source in some markdowns. Unfortunately they're not displayed if the URL has a trailing slash.

Is the only solution to use absolute URLs?

Image displayed: https://github.com/SpaceApi/SpaceApi
Image not displayed: https://github.com/SpaceApi/SpaceApi/

**Comment by tdfischer** [comment]
Yes.

**Comment by eastein** [comment]
Yeah, it is. That's how web browsers do it.

**Comment by slopjong** [comment]
It's not related to the browser directly. Browsers often append a missing trailing slash according to the RFC specification. But it's not always clear if http://example.com/test is a file or a directory. The RFC says it's a file but this path portion might be treated as a part of a website's routing mechanism.
