### ISSUE TITLE
clarify array / object

### ISSUE THREAD

**Issue by ghost** [SpaceApi-archive/SpaceApi#3]
Another suggestion would be to clarify the use of "array" in the
specification -- maybe use "associative array" or "object" when you mean
{"key":"value"} and only "array" when you mean ["a", "b", "c"]; at least on
the first read of the spec this tripped me up and the example did not seem
to make much sense immediately. The API-lint had the same problem for a
while, though that seems to be fixed now.

**Comment by slopjong** [comment]
The [reference](http://spaceapi.net/documentation#Reference) clearly says of what type a field is and the [examples](http://spaceapi.net/documentation#Examples) show how to use the fields.
