### ISSUE TITLE
to escape or not to escape?

### ISSUE THREAD

**Issue by ghost** [SpaceApi-archive/SpaceApi#4]
I am also not sure why the example includes both "http://" as well as
"http:\/\/". JSON specifies \/\/, though apparently a bunch of libraries do
not implement this encoding (including, incidentally, node.js :-/)

**Comment by slopjong** [comment]
Both are valid. Don't worry about escaped and non-escaped slashes.

**Comment by rohieb** [comment]
But then it should also be

``` json
    "wind":[{"name":"outside", "speed":0.3, "gust": 1, "unit":"m\/s", "direction":"SE"}],
```

and

``` json
   "feeds":[
     {"name":"blog","type":"application\/rss+xml","url":"https:\/\/revspace.nl\/blog.rss"},
     {"name":"calendar","type":"text\/calendar","url":"https:\/\/revspace.nl\/revspace.ical"}
   ],
```

**Comment by slopjong** [comment]
As already said, both are valid in JSON. Some libraries are reencoding automatically whilst others don't. Every library should read both variants, otherwise they're not working correctly.
