### ISSUE TITLE
widget available

### ISSUE THREAD

**Issue by ghost** [SpaceApi-archive/SpaceApi#5]
the widget is now more or less functional and the source can be found
at http://github.com/ktt-ol/hackspacewiget

**Comment by lhw** [comment]
You have a typo in the url. https://github.com/ktt-ol/hackspacewidget
Also the widget is still an early alpha version or rather a development version. Feature requests can be added to the issue tracker.

**Comment by slopjong** [comment]
Can somebody add this app [here](https://github.com/SpaceApi/spaceapiapp_app)? Edit model.json and put the screenshot to img.
